Tip 706 small business
jjanvier/pim-community-dev pull request #137
Opened 2017-04-13 11:52 UTC by SamirBoulil

**Description (for Contributor and Core Developer)**
- Sort using only propery `'missing' => '_last'`
- Regarding the check of a entity code before filtering within the PQB: the team chosed NOT to check for existing code and not to throw an exception. *(this may change in the near future, further discussions are occuring)*

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added Behats                      | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2017-04-13 15:35 UTC, skeleton requested changes
not GTM.
You cannot remove exception like that. You break some behaviors. For instance, on the API, if a user set a non existant locale, you have to throw an exception.
You want to remove them from the PQB, no problem about that, but you have to check somewhere if code is valid, or negotiate with PO to change this behavior (but as it's a BC break, there is no chance to change it).

2017-04-13 16:50 UTC, SamirBoulil commented
I'll revert the commit and do another PR to reactivate the check of the entity code within the filters themselves.

2017-04-13 17:55 UTC, jjanvier approved these changes

2017-04-14 09:22 UTC, damien-carcel approved these changes

2017-04-14 09:51 UTC, skeleton approved these changes

2017-04-14 09:57 UTC, merged