TIP-613: Fix rules execution
jjanvier/pim-community-dev pull request #216
Opened 2017-05-17 12:46 UTC by aRn0D

2017-05-17 14:06 UTC, damien-carcel requested changes
@jjanvier will confirm or infirm, but I think we decided to remove this operator.

So it should not be allowed in rules anymore either.

2017-05-17 14:06 UTC, damien-carcel commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
> +            case Operators::ENDS_WITH:
Didn't we decide to completely remove this operator?

2017-05-17 14:06 UTC, damien-carcel commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
> +            case Operators::ENDS_WITH:
@jjanvier

2017-05-17 14:19 UTC, jjanvier commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
> +            case Operators::ENDS_WITH:
I confirm

ENDS WITH has been removed with the approval of the POs

2017-05-17 14:23 UTC, aRn0D commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
> +            case Operators::ENDS_WITH:
ok !

2017-05-17 14:35 UTC, damien-carcel approved these changes

2017-05-17 14:45 UTC, damien-carcel commented on src/Pim/Component/Catalog/Factory/ProductValue/MetricProductValueFactory.php
> -                'unit'   => $attribute->getDefaultMetricUnit(),
To be sure this will not result in an API BC breack. But you will have fails on Integration tests and/or behats for sure.

2017-05-22 08:19 UTC, jjanvier approved these changes

2017-05-22 15:44 UTC, merged