TIP-709: indexing format to be used in ElasticSearch
jjanvier/pim-community-dev pull request #56
Opened 2017-03-15 08:49 UTC by jjanvier

[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

[//]: <> (What does this Pull Request do? reference the related issue?)

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added Behats                      | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2017-03-15 16:59 UTC, anaelChardan reviewed
Only questions

2017-03-15 16:59 UTC, anaelChardan commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    protected $stdNormalizer;
Just a question, why not standardNormalizer ? In my head, below when I see stdNormalizer and after stdValues it rings like stdClass values :/.

2017-03-15 16:59 UTC, anaelChardan commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    private function normalizePriceCollectionData(array $stdPrices)
same

2017-03-15 16:59 UTC, anaelChardan commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    protected $stdNormalizer;
Or it is and I would prefer stdClassNormalizer

2017-03-15 16:59 UTC, anaelChardan commented on src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/ProductValuesNormalizerSpec.php
> +        $this->shouldImplement('Symfony\Component\Serializer\Normalizer\NormalizerInterface');
When do we use MyInterface::class and when do we use FQCN ?

2017-03-15 16:59 UTC, anaelChardan commented on src/Pim/Component/Catalog/tests/integration/Normalizer/NormalizedProductCleaner.php
> +    private function ksortRecursive(&$array, $sort_flags = SORT_REGULAR)
Should be a static one :)

2017-03-15 17:04 UTC, SamirBoulil commented on src/Pim/Component/Catalog/Normalizer/Indexing/AttributeOptionNormalizer.php
> +        return $data instanceof AttributeOptionInterface && 'indexing' === $format;
maybe change 'indexing' for something that is not a verb like 'indexed'/'indexation' ? Not mandatory just a proposition

2017-03-15 17:04 UTC, BitOne commented
As the indexing format main purpose is to serve search queries, I don't get why it's based on the standard format which has not the same purpose.

More precisely, we shouldn't even have normalizer for field for which we don't have a filter. For example, the file normalizer.

2017-03-15 17:06 UTC, SamirBoulil commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> + * Normalize a product value to the indexing format.
👍

2017-03-15 17:06 UTC, BitOne requested changes

2017-03-15 17:06 UTC, BitOne commented on src/Pim/Component/Catalog/Normalizer/Indexing/DateTimeNormalizer.php
> + * @author    Julien Janvier <jjanvier@akeneo.com>
Not sure that this address exists ;p

2017-03-15 17:06 UTC, BitOne commented on src/Pim/Bundle/CatalogBundle/Resources/config/serializers_indexing.yml
> +            - { name: pim_serializer.normalizer, priority: 90 }
Shouldn't we have a dedicated normalizer instead on relying on the generic (and over-used) pim_serializer ?

2017-03-15 17:06 UTC, BitOne commented on src/Pim/Component/Catalog/Normalizer/Indexing/FileNormalizer.php
> + * This format is based on the standard format.
Why?

2017-03-15 17:08 UTC, damien-carcel approved these changes

2017-03-15 17:08 UTC, damien-carcel commented on src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php
> +    protected function getConfiguration()
`{@inheritdoc}`

2017-03-15 17:20 UTC, jjanvier commented
@BitOne 

> As the indexing format main purpose is to serve search queries, I don't get why it's based on the standard format which has not the same purpose.

2 reasons: 
- because even if they are not indexed the same way, the data really are the same between our different formats (standard, indexing, storage). So I think it could be relevant to be based on the standard format, at least for the data.
- for commodity because it helped us to to code faster (not a good reason, we agree, please see below)

> More precisely, we shouldn't even have normalizer for field for which we don't have a filter. For example, the file normalizer.

I completely agree. We have all these useless normalizers currently because we are doing some really really unusual and weird things with the Symfony serializers/normalizers. Please see [this conversation](https://github.com/akeneo/pim-community-dev/pull/5418#discussion_r95167513) for instance. 

My plan was to:
- first, introduce quickly this indexing format (the most important class in the PR is the integration test imo). Using the standard normalizers is just a way to achieve that, not a goal or a will.
- then, in another PR, review all our serialzers/normalizers (versioning, standard, ui, indexing, storage) stack to not be forced to write dirty things like what I had to do here

2017-03-15 17:25 UTC, BitOne commented
@jjanvier:

So if I understand correctly, this is not the final indexing format, but just a quick way to have some data in Elasticsearch.

If that's the case, your plan is missing a "Build the real final indexing format" as step 2.

And yes, the normalizer stuff is a issue, but a different one.

2017-03-16 07:08 UTC, jjanvier commented
@BitOne it should be the final indexing format (unless we missed some stuff)
but maybe not the way to build it

IRL this morning?

2017-03-16 10:33 UTC, jjanvier commented
Seen IRL with Benoit.
We'll do another way.
Each filter will normalizes its small part of the product.

2017-03-16 10:33 UTC, closed without merging

2017-03-16 10:34 UTC, jjanvier commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    protected $stdNormalizer;
ok $standardNormalizer would be better
just a copy/paste I guess

2017-03-16 10:34 UTC, jjanvier commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    private function normalizePriceCollectionData(array $stdPrices)
same what?

2017-03-16 10:34 UTC, jjanvier commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    private function normalizePriceCollectionData(array $stdPrices)
$standardPrices would be better

2017-03-16 10:35 UTC, anaelChardan commented on src/Pim/Component/Catalog/Normalizer/Indexing/Product/ProductValueNormalizer.php
> +    protected $stdNormalizer;
Thanks seigneur jj

2017-03-16 10:35 UTC, jjanvier commented on src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/ProductValuesNormalizerSpec.php
> +        $this->shouldImplement('Symfony\Component\Serializer\Normalizer\NormalizerInterface');
use MyInterface::class whenever you can
it's a copy/paste I guess

2017-03-16 10:35 UTC, jjanvier commented on src/Pim/Component/Catalog/tests/integration/Normalizer/NormalizedProductCleaner.php
> +    private function ksortRecursive(&$array, $sort_flags = SORT_REGULAR)
agree

2017-03-16 10:35 UTC, jjanvier commented on src/Pim/Bundle/CatalogBundle/Resources/config/serializers_indexing.yml
> +            - { name: pim_serializer.normalizer, priority: 90 }
yep agree