Tip 706 datetime sorter
jjanvier/pim-community-dev pull request #89
Opened 2017-03-24 15:25 UTC by anaelChardan

[//]: <> (<3 Thanks for taking the time to contribute! You're awesome! <3)

[//]: <> (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-community-dev/blob/master/.github/CONTRIBUTING.md)

**Description (for Contributor and Core Developer)**

[//]: <> (What does this Pull Request do? reference the related issue?)

**Definition Of Done (for Core Developer only)**

| Q                                 | A
| --------------------------------- | ---
| Added Specs                       | Todo
| Added Behats                      | Todo
| Added integration tests           | Todo
| Changelog updated                 | Todo
| Review and 2 GTM                  | Todo
| Micro Demo to the PO (Story only) | Todo
| Migration script                  | -
| Tech Doc                          | -

`Todo`: Pending / Work in progress
`OK`: Done / Validated
`-`: Not needed

2017-03-24 15:36 UTC, SamirBoulil commented on src/Pim/Component/Catalog/Exception/InvalidDirectionException.php
> +    const NOT_SUPPORTED_CODE = 300;
Check if it should be the same as operator code

2017-03-30 06:23 UTC, jjanvier requested changes
not GTM about the cursor
I want to double check with Marie and you IRL
there is something I don't understand

all the other is good :+1:

2017-03-30 06:23 UTC, jjanvier commented on src/Akeneo/Bundle/ElasticsearchBundle/Cursor/Cursor.php
> +        $nextItems = array_map(function ($identifier) use ($hydratedProducts) {
I don't understand what you do here
we should double check with @skeleton

2017-03-30 06:23 UTC, jjanvier commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/BaseSorter.php
> +                        "missing" => "_first"
are we sure about that?
did we check with Delphine that's the behavior she wants?

2017-03-30 06:23 UTC, jjanvier commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/BaseSorter.php
> +                        "missing" => "_last"
are we sure about that?
did we check with Delphine that's the behavior she wants?

2017-03-30 06:23 UTC, jjanvier commented on src/Pim/Bundle/CatalogBundle/tests/integration/PQB/AbstractProductQueryBuilderTestCase.php
> +    protected function assertOrder($result, array $expected)
typehint!!!

2017-03-30 06:42 UTC, anaelChardan commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/BaseSorter.php
> +                        "missing" => "_last"
Yes

2017-03-30 06:42 UTC, anaelChardan commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/BaseSorter.php
> +                        "missing" => "_first"
Yes :)

2017-03-30 06:43 UTC, anaelChardan commented
Yes, we should talk about this one IRL :)

2017-03-30 12:50 UTC, anaelChardan commented on src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/BaseSorter.php
> +                        "missing" => "_first"
So for this question, this will be harmonized in another PR :) (seen with Delph :))

2017-03-30 13:02 UTC, SamirBoulil commented on src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Sorter/BaseSorterSpec.php
> +}
add new line (I can show you my conf if needed ;) )

2017-03-30 13:05 UTC, SamirBoulil approved these changes
GTM if integration tests of the merged filters are green.

2017-03-30 13:46 UTC, jjanvier approved these changes
GTM

2017-03-30 13:46 UTC, jjanvier commented on src/Akeneo/Bundle/ElasticsearchBundle/Cursor/Cursor.php
> +                    $orderedItems[] = $hydratedItem;
break

2017-03-30 14:14 UTC, anaelChardan commented
https://core-ci.akeneo.com/blue/organizations/jenkins/jjanvier%2Fpim-community-dev/detail/PR-89/9/tests/

2017-03-30 14:14 UTC, merged